[package]
name = "bin"
version = "0.1.0"
edition = "2021"
authors = ["zCloak Network"]

[[bin]]
name = "zcloak-keeper"
path = "src/main.rs"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
async-trait = "0.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = { version = "1.3.1", optional = true }
tokio = { version = "1", features = ["full"] }
config = "0.11"
structopt = "0.3"
secp256k1 = { version = "0.21", features = ["recovery"] }
env_logger = "0.9.0"
hex = "0.4"
futures = "0.3.21"
#msq
yaque = "0.6.3"

# self
keeper-primitives = { path = "../primitives" }
moonbeam = { package = "component-moonbeam", path = "../moonbeam" }
ipfs = { package = "component-ipfs", path = "../ipfs" }
kilt = { package = "component-kilt", path = "../kilt" }

[features]
monitor = ["keeper-primitives/monitor", "moonbeam/monitor"]
